version: "3.9"
services:
  albert_mosquitto:
    image: eclipse-mosquitto:1.6.12

  # # dakota_mosquitto:
  # #   image: eclipse-mosquitto:1.6.12

  # # tiffany_mosquitto:
  # #   image: eclipse-mosquitto:1.6.12

  # # tommy_mosquitto:
  # #   image: eclipse-mosquitto:1.6.12

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  albert-presence-sensor:
    build:
      context: ./Sensors/presence_sensor
      dockerfile: Dockerfile
    container_name: albert_presence_sensor
    environment:
      - mqtt=albert_mosquitto
    depends_on:
      - albert_mosquitto

  # albert-temp-sensor:
  #   build:
  #     context: ./Sensors/temp_sensor
  #     dockerfile: Dockerfile
  #   container_name: albert_temp_sensor
  #   environment:
  #     - mqtt=albert_mosquitto
  #   depends_on:
  #     - albert_mosquitto

  albert-gateway:
    build:
      context: ./Gateways
      dockerfile: Dockerfile
    container_name: albert_gateway
    environment:
      - mqtt=albert_mosquitto
    depends_on:
      - kafka
      - albert_mosquitto
      
  save-processor:
    build:
      context: ./Kafka/save-processor
      dockerfile: Dockerfile
    container_name: save-processor
    depends_on:
      - kafka

  # dakota-presence-sensor:
  #   build:
  #     context: ./Sensors/presence_sensor
  #     dockerfile: Dockerfile
  #   container_name: dakora_presence_sensor
  #   environment:
  #     - mqtt=dakota_mosquitto
  #   depends_on:
  #     - dakota_mosquitto

  # dakota-temp-sensor:
  #   build:
  #     context: ./Sensors/temp_sensor
  #     dockerfile: Dockerfile
  #   container_name: dakota_temp_sensor
  #   environment:
  #     - mqtt=dakota_mosquitto
  #   depends_on:
  #     - dakota_mosquitto

  # tiffany-presence-sensor:
  #   build:
  #     context: ./Sensors/presence_sensor
  #     dockerfile: Dockerfile
  #   container_name: tiffany_presence_sensor
  #   environment:
  #     - mqtt=tiffany_mosquitto
  #   depends_on:
  #     - tiffany_mosquitto

  # tiffany-temp-sensor:
  #   build:
  #     context: ./Sensors/temp_sensor
  #     dockerfile: Dockerfile
  #   container_name: tiffany_temp_sensor
  #   environment:
  #     - mqtt=tiffany_mosquitto
  #   depends_on:
  #     - tiffany_mosquitto

  # tommy-presence-sensor:
  #   build:
  #     context: ./Sensors/presence_sensor
  #     dockerfile: Dockerfile
  #   container_name: tommy_presence_sensor
  #   environment:
  #     - mqtt=tommy_mosquitto
  #   depends_on:
  #     - tommy_mosquitto

  # tommy-temp-sensor:
  #   build:
  #     context: ./Sensors/temp_sensor
  #     dockerfile: Dockerfile
  #   container_name: tommy_temp_sensor
  #   environment:
  #     - mqtt=tommy_mosquitto
  #   depends_on:
  #     - tommy_mosquitto

