version: "3.9"
services:
  albert_mosquitto:
    container_name: albert_mosquitto
    image: eclipse-mosquitto:1.6.12
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwords.txt:/mosquitto/config/passwords.txt

  dakota_mosquitto:
    container_name: dakota_mosquitto
    image: eclipse-mosquitto:1.6.12
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwords.txt:/mosquitto/config/passwords.txt

  # tiffany_mosquitto:
  #   image: eclipse-mosquitto:1.6.12

  # tommy_mosquitto:
  #   image: eclipse-mosquitto:1.6.12

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  influxdb:
    image: influxdb:2.4.0
    ports:
      - "8086:8086"
    container_name: influxDB
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=1234567890
      - DOCKER_INFLUXDB_INIT_ORG=udl
      - DOCKER_INFLUXDB_INIT_BUCKET=iotproject
    volumes:
      - ./influxdb_docker/influx-data:/var/lib/influxdb2
      
  save-processor:
    build:
      context: ./Kafka/save-processor
      dockerfile: Dockerfile
    environment:
      - DOCKER_INFLUXDB_INIT_BUCKET=iotproject
      - DOCKER_INFLUXDB_INIT_ORG=udl
      - DOCKER_INFLUXDB_INIT_URL=http://influxdb:8086
      - DOCKER_INFLUXDB_INIT_TOKEN=Ry-ExejcbAAGmVO3azDAZ5eZo8Ck_ZIot3kAyHElvbgxvGQrZOMe29CVYShptOVhM2ss3zASkoRRDB9RX8L67Q==
      - DOCKER_KAFKA_INIT_TOKEN=kafka:9092
      - GROUP_ID=save-consumer-group
    depends_on:
      - kafka
      - influxdb
    deploy:
        replicas: 3

  clean-processor:
    build:
      context: ./Kafka/clean-processor
      dockerfile: Dockerfile
    container_name: kafka-clean
    environment:
      - DOCKER_KAFKA_INIT_TOKEN=kafka:9092
    depends_on:
      - kafka

  actuator-processor:
    build:
      context: ./Kafka/actuate-processor
      dockerfile: Dockerfile
    container_name: kafka-actuate
    environment:
      - DOCKER_KAFKA_INIT_TOKEN=kafka:9092
      - mqtt_albert=albert_mosquitto
      - mqtt_tiffany=tiffany_mosquitto
      - mqtt_dakota=dakota_mosquitto
      - mqtt_tommy=tommy_mosquitto
    depends_on:
      - kafka
      - albert_mosquitto
    

  #-------------------------------------------------Albert----------------------------------------------------------
  
  albert-presence:
    build:
      context: ./Sensors/presence_sensor
      dockerfile: Dockerfile
    container_name: albert_presence
    environment:
      - mqtt=albert_mosquitto
    depends_on:
      - albert_mosquitto

  albert-temperature:
    build:
      context: ./Sensors/temp_sensor
      dockerfile: Dockerfile
    container_name: albert_temp_sensor
    environment:
      - mqtt=albert_mosquitto
    depends_on:
      - albert_mosquitto

  albert-gateway:
    build:
      context: ./Gateways
      dockerfile: Dockerfile
    container_name: albert_gateway
    environment:
      - mqtt=albert_mosquitto
      - user=albert
      - DOCKER_KAFKA_INIT_TOKEN=kafka:9092
    depends_on:
      - kafka
      - albert_mosquitto

  albert-heat-pump:
    build:
      context: ./Actuators/heat_pump
      dockerfile: Dockerfile
    container_name: albert-heatPump
    environment:
      - mqtt=albert_mosquitto
    depends_on:
      - albert_mosquitto

  albert-light-bulb:
    build:
      context: ./Actuators/light_bulb
      dockerfile: Dockerfile
    container_name: albert-lightBulb
    environment:
      - mqtt=albert_mosquitto
    depends_on:
      - albert_mosquitto

  #-------------------------------------------------Dakota----------------------------------------------------------

  dakota-presence:
    build:
      context: ./Sensors/presence_sensor
      dockerfile: Dockerfile
    container_name: dakota_presence
    environment:
      - mqtt=dakota_mosquitto
    depends_on:
      - dakota_mosquitto

  dakota-temperature:
    build:
      context: ./Sensors/temp_sensor
      dockerfile: Dockerfile
    container_name: dakota_temp_sensor
    environment:
      - mqtt=dakota_mosquitto
    depends_on:
      - dakota_mosquitto

  dakota-gateway:
    build:
      context: ./Gateways
      dockerfile: Dockerfile
    container_name: dakota_gateway
    environment:
      - mqtt=dakota_mosquitto
      - user=dakota
      - DOCKER_KAFKA_INIT_TOKEN=kafka:9092
    depends_on:
      - kafka
      - dakota_mosquitto

  dakota-heat-pump:
    build:
      context: ./Actuators/heat_pump
      dockerfile: Dockerfile
    container_name: dakota-heatPump
    environment:
      - mqtt=dakota_mosquitto
    depends_on:
      - dakota_mosquitto

  dakota-light-bulb:
    build:
      context: ./Actuators/light_bulb
      dockerfile: Dockerfile
    container_name: dakota-lightBulb
    environment:
      - mqtt=dakota_mosquitto
    depends_on:
      - dakota_mosquitto

  #-------------------------------------------------Tiffany----------------------------------------------------------

  # tiffany-presence-sensor:
  #   build:
  #     context: ./Sensors/presence_sensor
  #     dockerfile: Dockerfile
  #   container_name: tiffany_presence_sensor
  #   environment:
  #     - mqtt=tiffany_mosquitto
  #   depends_on:
  #     - tiffany_mosquitto

  # tiffany-temp-sensor:
  #   build:
  #     context: ./Sensors/temp_sensor
  #     dockerfile: Dockerfile
  #   container_name: tiffany_temp_sensor
  #   environment:
  #     - mqtt=tiffany_mosquitto
  #   depends_on:
  #     - tiffany_mosquitto

  # tiffany-gateway:
  #   build:
  #     context: ./Gateways
  #     dockerfile: Dockerfile
  #   container_name: tiffany_gateway
  #   environment:
  #     - mqtt=tiffany_mosquitto
  #     - user=tiffany
  #     - DOCKER_KAFKA_INIT_TOKEN=kafka:9092
  #   depends_on:
  #     - kafka
  #     - tiffany_mosquitto

  # tiffany-heat-pump:
  #   build:
  #     context: ./Actuators/heat_pump
  #     dockerfile: Dockerfile
  #   container_name: tiffany-heatPump
  #   environment:
  #     - mqtt=tiffany_mosquitto
  #   depends_on:
  #     - tiffany_mosquitto

  # tiffany-light-bulb:
  #   build:
  #     context: ./Actuators/light_bulb
  #     dockerfile: Dockerfile
  #   container_name: tiffany-lightBulb
  #   environment:
  #     - mqtt=tiffany_mosquitto
  #   depends_on:
  #     - tiffany_mosquitto

  #-------------------------------------------------Tommy----------------------------------------------------------

  # tommy-presence-sensor:
  #   build:
  #     context: ./Sensors/presence_sensor
  #     dockerfile: Dockerfile
  #   container_name: tommy_presence_sensor
  #   environment:
  #     - mqtt=tommy_mosquitto
  #   depends_on:
  #     - tommy_mosquitto

  # tommy-temp-sensor:
  #   build:
  #     context: ./Sensors/temp_sensor
  #     dockerfile: Dockerfile
  #   container_name: tommy_temp_sensor
  #   environment:
  #     - mqtt=tommy_mosquitto
  #   depends_on:
  #     - tommy_mosquitto
  
  # tommy-gateway:
  #   build:
  #     context: ./Gateways
  #     dockerfile: Dockerfile
  #   container_name: tommy_gateway
  #   environment:
  #     - mqtt=tommy_mosquitto
  #     - user=tommy
  #     - DOCKER_KAFKA_INIT_TOKEN=kafka:9092
  #   depends_on:
  #     - kafka
  #     - tommy_mosquitto

  # tommy-heat-pump:
  #   build:
  #     context: ./Actuators/heat_pump
  #     dockerfile: Dockerfile
  #   container_name: tommy-heatPump
  #   environment:
  #     - mqtt=tommy_mosquitto
  #   depends_on:
  #     - tommy_mosquitto

  # tommy-light-bulb:
  #   build:
  #     context: ./Actuators/light_bulb
  #     dockerfile: Dockerfile
  #   container_name: tommy-lightBulb
  #   environment:
  #     - mqtt=tommy_mosquitto
  #   depends_on:
  #     - tommy_mosquitto